/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package qcalc.com.crio;

public class App{
public static void main(String[] args) {
    
    System.out.println(new App().getGreeting());;
    
    ScientificCalculator calc = new ScientificCalculator();

    double result= calc.cubeOf(4.0);

    System.out.println("cube =" + result);

}

public String getGreeting() {
    return null;
}

}